"""empty message

Revision ID: 572ae7d6bb3d
Revises: 
Create Date: 2019-10-27 03:35:59.363619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572ae7d6bb3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=127), nullable=False),
    sa.Column('macaddress', sa.String(length=31), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bows')
    # ### end Alembic commands ###
